using NUnit.Framework;

namespace AdventOfCode2025.Day7.Tests;

public static class SolutionDay7Tests
{
	[Test]
	public static void Part1()
	{
		var input =
			"""
			.......S.......
			...............
			.......^.......
			...............
			......^.^......
			...............
			.....^.^.^.....
			...............
			....^.^...^....
			...............
			...^.^...^.^...
			...............
			..^...^.....^..
			...............
			.^.^.^.^.^...^.
			...............
			""";

		Assert.That(SolutionDay7.RunPart1([.. input.Split(Environment.NewLine)]), Is.EqualTo(21u));
	}
}